# Name of action/workflow/job
name: Run Pandas Job

# When to do
# Triggers for workflow
on:
  # event based triggers
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  # time based trigger
  schedule:
    - cron: '0 0 * * *'


# What to do
# Action/workflow/job
jobs:
  run_pandas_job: ubuntu-latest
  steps:
    - name: Checkout Code
      # owner/repo@version
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: pip install pandas
    
    - name: Run Pandas Job
      run: python app.py